let skills = {
  fastapi:{title:'FASTAPI',level:8,confidence:94,reason:'Your repositories show repeated production use of async APIs, dependency injection, middleware, authentication and streaming responses.',caps:[['✓','Async API'],['✓','Dependency Injection'],['✓','Middleware'],['✓','Authentication'],['✓','SSE'],['△','Testing'],['✕','Observability']],evidence:[['DustGuard / api/routes/chat.py : 42','Streams LLM output through an async StreamingResponse endpoint.'],['DustGuard / api/dependencies/auth.py : 18','Implements reusable token validation with FastAPI dependency injection.'],['PaperPilot / server/middleware/timing.py : 09','Adds request latency metadata through custom ASGI middleware.']],next:'Add integration tests and production observability to reach Level 9.'},
  python:{title:'PYTHON',level:9,confidence:97,reason:'Eight repositories demonstrate advanced Python patterns across async services, typed domain models, data pipelines and packaging.',caps:[['✓','Async IO'],['✓','Type System'],['✓','Packaging'],['✓','Data Models'],['✓','Architecture'],['△','Profiling']],evidence:[['DustGuard / core/pipeline.py : 31','Coordinates typed async stages with explicit failure handling.'],['PaperPilot / pyproject.toml : 01','Ships a reproducible package with constrained dependencies.'],['SignalLab / models/events.py : 14','Uses generic protocols to separate domain logic from adapters.']],next:'Show profiling and performance optimization in a production workload to reach Level 10.'},
  api:{title:'API DESIGN',level:8,confidence:91,reason:'Your APIs use consistent resource models, structured errors, versioning and streaming where the interaction demands it.',caps:[['✓','REST'],['✓','Versioning'],['✓','Error Models'],['✓','Streaming'],['△','Rate Limits']],evidence:[['DustGuard / api/v1/router.py : 12','Composes versioned route groups behind a stable public prefix.'],['PaperPilot / api/errors.py : 24','Maps domain exceptions to consistent machine-readable errors.']],next:'Implement rate limits and publish an API compatibility policy.'},
  llm:{title:'LLM',level:6,confidence:86,reason:'You integrate multiple model providers, stream generation and manage prompt templates, but evaluation evidence is still missing.',caps:[['✓','Streaming'],['✓','Providers'],['✓','Prompting'],['△','Guardrails'],['✕','Evaluation']],evidence:[['DustGuard / llm/provider.py : 55','Normalizes streaming events across two model providers.'],['PaperPilot / prompts/extract.py : 07','Separates versioned extraction instructions from runtime code.']],next:'Add an evaluation harness with a versioned dataset and failure taxonomy.'},
  testing:{title:'TESTING',level:2,confidence:88,reason:'Only one repository contains meaningful automated tests. The current evidence covers utilities, not service behavior.',caps:[['✓','Unit Tests'],['△','Fixtures'],['✕','API Integration'],['✕','Mocking'],['✕','Coverage']],evidence:[['SignalLab / tests/test_parser.py : 11','Covers parser edge cases with parameterized unit tests.']],next:'Complete The Testing Dungeon to establish integration-test evidence.'},
  database:{title:'DATABASES',level:7,confidence:89,reason:'Your code demonstrates schema design, migrations, transaction handling and optimized queries across four repositories.',caps:[['✓','PostgreSQL'],['✓','Migrations'],['✓','Transactions'],['✓','Indexes'],['△','Replication']],evidence:[['DustGuard / db/models/session.py : 17','Models indexed session ownership and cascading lifecycle rules.'],['Ledger / migrations/004_event_index.sql : 03','Adds a compound index matching the production query path.']],next:'Demonstrate replication or partitioning decisions at production scale.'},
  rag:{title:'RAG',level:5,confidence:82,reason:'You have working chunking, embedding and retrieval flows, with limited evidence for measurement or retrieval quality.',caps:[['✓','Chunking'],['✓','Embeddings'],['✓','Vector Search'],['△','Reranking'],['✕','Evaluation']],evidence:[['PaperPilot / retrieval/index.py : 29','Builds metadata-aware vector documents from semantic sections.'],['PaperPilot / retrieval/search.py : 44','Combines similarity thresholding with document-level filters.']],next:'Add retrieval evaluation and a reranking experiment to reach Level 6.'},
  agents:{title:'AGENTS',level:4,confidence:78,reason:'Two projects use tool calling and multi-step orchestration. Evidence for durable state and recovery is limited.',caps:[['✓','Tool Calling'],['✓','Planning'],['△','State'],['✕','Recovery'],['✕','Evaluation']],evidence:[['Scout / agent/tools.py : 20','Defines typed tool contracts with validated arguments.'],['Scout / agent/loop.py : 61','Runs bounded tool iterations with explicit stop conditions.']],next:'Implement durable state, replay and recovery from tool failures.'},
  evaluation:{title:'EVALUATION',level:0,confidence:0,reason:'No reliable code signal has been discovered yet. This is unknown—not a claim that you lack the skill.',caps:[['✕','Datasets'],['✕','Metrics'],['✕','Regression'],['✕','Tracing']],evidence:[],next:'Ship a small, versioned evaluation suite to reveal this node.'}
};

const drawer=document.querySelector('#evidenceDrawer'),backdrop=document.querySelector('#drawerBackdrop');
function openSkill(key){const s=skills[key];if(!s)return;const caps=s.caps||s.capabilities||[];const evidence=s.evidence||[];document.querySelector('#skillTitle').textContent=s.title;document.querySelector('#skillLevel').textContent=s.level||'?';document.querySelector('#whyLevel').textContent=s.level||'?';document.querySelector('#skillConfidence').textContent=s.confidence?s.confidence+'%':'NO SIGNAL';document.querySelector('#confidenceBar').style.width=s.confidence+'%';document.querySelector('#skillReason').textContent=s.reason;document.querySelector('#capabilities').innerHTML=caps.map(c=>`<span class="${c[0]==='✓'?'':'missing'}">${c[0]} ${c[1]}</span>`).join('');document.querySelector('#evidenceCount').textContent=String(evidence.length).padStart(2,'0')+' SIGNALS';document.querySelector('#evidenceList').innerHTML=evidence.length?evidence.map(e=>{const item=Array.isArray(e)?{summary:e[1],repositoryPath:e[0]}:{...e,repositoryPath:`${e.repository} / ${e.path} : ${e.line}`};return `<article class="evidence-item"><span>◆ VERIFIED PATTERN / ${item.capability||'CODE'}</span><p>${item.summary}</p>${item.url?`<a href="${item.url}" target="_blank" rel="noreferrer"><code>${item.repositoryPath} ↗</code></a>`:`<code>${item.repositoryPath}</code>`}</article>`}).join(''):'<article class="evidence-item"><p>No inspectable evidence found in the indexed repositories.</p></article>';document.querySelector('#nextLevel').textContent=s.next;drawer.classList.add('open');backdrop.classList.add('open');drawer.setAttribute('aria-hidden','false')}
function closeDrawer(){drawer.classList.remove('open');backdrop.classList.remove('open');drawer.setAttribute('aria-hidden','true')}
document.querySelectorAll('.skill-node').forEach(n=>n.addEventListener('click',()=>openSkill(n.dataset.skill)));
document.querySelector('#drawerClose').addEventListener('click',closeDrawer);backdrop.addEventListener('click',closeDrawer);
document.querySelectorAll('.tree-toolbar button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tree-toolbar button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.skill-node').forEach(n=>n.classList.toggle('hidden',btn.dataset.filter!=='all'&&n.dataset.domain!==btn.dataset.filter))}));
const modal=document.querySelector('#scoreModal');document.querySelector('#explainBtn').addEventListener('click',()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false')});document.querySelector('#modalClose').addEventListener('click',()=>modal.classList.remove('open'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});
const toast=document.querySelector('#toast');let toastTimer;document.querySelectorAll('[data-toast]').forEach(b=>b.addEventListener('click',()=>{toast.querySelector('b').textContent=b.dataset.toast;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeDrawer();modal.classList.remove('open')}});

const syncButton=document.querySelector('#syncGithub');
const scanOverlay=document.querySelector('#scanOverlay');
function showToast(message){toast.querySelector('b').textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),3000)}
function initials(name){return name.split(/\s+/).map(part=>part[0]).join('').slice(0,2).toUpperCase()}
function setProfile(profile){const name=(profile.name||profile.login||'Developer').trim();const pieces=name.split(/\s+/);document.querySelector('#passportName').innerHTML=pieces.length>1?`${pieces[0]}<br>${pieces.slice(1).join(' ')}`:name;document.querySelector('#profileAvatar').textContent=initials(name);if(profile.overallLevel)document.querySelector('#overallLevel').textContent=profile.overallLevel;if(profile.repositoryCount!=null)document.querySelector('#repoCount').textContent=`${profile.repositoryCount} VERIFIED`}
function renderAnalysis(data){skills={...skills,...data.skills};Object.entries(data.skills).forEach(([key,skill])=>{const node=document.querySelector(`[data-skill="${key}"]`);if(!node)return;node.querySelector('.node-ring b').textContent=skill.score||'?';node.querySelector('.node-ring small').textContent=skill.level?`LV.${skill.level}`:'LOCKED';node.querySelector(':scope > small').textContent=`${skill.evidence.length} EVIDENCE`;node.classList.toggle('locked',skill.level===0);node.classList.toggle('emerging',skill.level>0&&skill.level<6)});setProfile(data.profile);document.querySelector('#scanState').textContent='CODE INDEXED';document.querySelector('#scanTime').textContent='JUST NOW';document.querySelector('.tree-count').textContent=`${Object.values(data.skills).filter(skill=>skill.level>0).length} / ${Object.keys(data.skills).length} NODES DISCOVERED`;syncButton.innerHTML='RESCAN CODE <span>↗</span>'}
async function runScan(){scanOverlay.classList.add('open');scanOverlay.setAttribute('aria-hidden','false');const logs=['READING REPOSITORY TREES','SELECTING SOURCE EVIDENCE','VERIFYING IMPLEMENTATION PATTERNS','CALCULATING SKILL GRAPH'];let step=0;const ticker=setInterval(()=>{document.querySelector('#scanLog').textContent=logs[step++%logs.length]},900);try{const response=await fetch('/api/analyze',{method:'POST'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Scan failed');renderAnalysis(data);showToast(`${data.filesInspected} files verified across ${data.profile.repositoryCount} repositories`)}catch(error){showToast(error.message)}finally{clearInterval(ticker);scanOverlay.classList.remove('open');scanOverlay.setAttribute('aria-hidden','true');history.replaceState({},'',location.pathname)}}
async function initializeAuth(){try{const response=await fetch('/api/auth/status');const state=await response.json();if(state.connected){setProfile(state.user);syncButton.innerHTML='SCAN MY CODE <span>↗</span>';syncButton.addEventListener('click',runScan);if(new URLSearchParams(location.search).has('connected'))runScan()}else{syncButton.addEventListener('click',()=>{if(state.oauthConfigured)location.href='/api/auth/github';else{showToast('OAuth is not configured — exploring verified demo data');document.querySelector('#tree').scrollIntoView({behavior:'smooth'})}});if(new URLSearchParams(location.search).has('demo'))showToast('Demo mode — add GitHub OAuth credentials to scan real code')} }catch{syncButton.addEventListener('click',()=>showToast('API unavailable — demo mode remains active'))}}
initializeAuth();
