import type { AnalysisResult, AuthState, DeveloperProfile, ScanRecord, ScanStage, Skill, SkillKey } from '../shared/types.js';

type UiSkill = Omit<Skill, 'score' | 'repositoryCount'> & { score?: number; repositoryCount?: number };
const skillKeys: SkillKey[] = ['python', 'fastapi', 'api', 'llm', 'testing', 'database', 'rag', 'agents', 'evaluation'];
const demo = (title: string, level: number, confidence: number, reason: string, capabilities: Skill['capabilities'], next: string): UiSkill => ({ title, level, confidence, reason, capabilities, next, evidence: [] });
let skills: Record<SkillKey, UiSkill> = {
  python: demo('PYTHON',9,97,'Advanced Python patterns appear across async services, typed models, packaging and data pipelines.',[['✓','Async IO'],['✓','Type System'],['✓','Packaging'],['✓','Data Models'],['△','Profiling']],'Show production profiling evidence to reach Level 10.'),
  fastapi: demo('FASTAPI',8,94,'Repeated production use of async APIs, dependency injection, middleware, authentication and streaming responses.',[['✓','Async API'],['✓','Dependency Injection'],['✓','Middleware'],['✓','Authentication'],['✓','SSE'],['△','Testing'],['✕','Observability']],'Add integration tests and observability to reach Level 9.'),
  api: demo('API DESIGN',8,91,'The APIs use consistent resources, structured errors, versioning and streaming.',[['✓','REST'],['✓','Versioning'],['✓','Error Models'],['✓','Streaming'],['△','Rate Limits']],'Implement rate limits and publish a compatibility policy.'),
  llm: demo('LLM',6,86,'Model providers, streaming and prompt templates are implemented; evaluation evidence is still missing.',[['✓','Streaming'],['✓','Providers'],['✓','Prompting'],['△','Guardrails'],['✕','Evaluation']],'Add a versioned evaluation harness.'),
  testing: demo('TESTING',2,88,'Current evidence covers utilities but not enough service behavior.',[['✓','Unit Tests'],['△','Fixtures'],['✕','API Integration'],['✕','Mocking'],['✕','Coverage']],'Complete The Testing Dungeon.'),
  database: demo('DATABASES',7,89,'Schema design, migrations, transactions and optimized queries appear across multiple projects.',[['✓','PostgreSQL'],['✓','Migrations'],['✓','Transactions'],['✓','Indexes'],['△','Replication']],'Show partitioning or replication decisions.'),
  rag: demo('RAG',5,82,'Chunking, embeddings and retrieval are implemented with limited quality measurement.',[['✓','Chunking'],['✓','Embeddings'],['✓','Vector Search'],['△','Reranking'],['✕','Evaluation']],'Add retrieval evaluation and reranking.'),
  agents: demo('AGENTS',4,78,'Tool calling and orchestration exist; durable state and recovery remain limited.',[['✓','Tool Calling'],['✓','Planning'],['△','State'],['✕','Recovery'],['✕','Evaluation']],'Implement durable state and replay.'),
  evaluation: demo('EVALUATION',0,0,'No reliable code signal has been discovered. This is unknown, not a negative assessment.',[['✕','Datasets'],['✕','Metrics'],['✕','Regression'],['✕','Tracing']],'Ship a small versioned evaluation suite.')
};

function must<T extends Element>(selector: string): T { const node=document.querySelector<T>(selector); if(!node)throw new Error(`Missing UI element: ${selector}`); return node; }
function child<T extends Element>(root: Element, selector: string): T { const node=root.querySelector<T>(selector); if(!node)throw new Error(`Missing child: ${selector}`); return node; }
const drawer=must<HTMLElement>('#evidenceDrawer'), backdrop=must<HTMLElement>('#drawerBackdrop'), modal=must<HTMLElement>('#scoreModal');
const toast=must<HTMLElement>('#toast'), syncButton=must<HTMLButtonElement>('#syncGithub'), logoutButton=must<HTMLButtonElement>('#logoutButton');
const scanOverlay=must<HTMLElement>('#scanOverlay'), scanRetry=must<HTMLButtonElement>('#scanRetry'), scanClose=must<HTMLButtonElement>('#scanClose');
let toastTimer: ReturnType<typeof setTimeout>|undefined, authStatePromise: Promise<AuthState>|undefined, activeScan=false;

function showToast(message:string){must<HTMLElement>('#toast b').textContent=message;toast.classList.add('show');if(toastTimer)clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),3200)}
async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(path,{cache:'no-store',...init});const data=await response.json().catch(()=>({})) as T&{error?:string};if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data}
function initials(name:string){return name.split(/\s+/).filter(Boolean).map(part=>part[0]||'').join('').slice(0,2).toUpperCase()}
function setProfile(profile:DeveloperProfile){const name=(profile.name||profile.login||'Developer').trim();must<HTMLElement>('#passportName').innerHTML=name.split(/\s+/).join('<br>');must<HTMLElement>('#profileAvatar').textContent=initials(name);if(profile.overallLevel)must<HTMLElement>('#overallLevel').textContent=String(profile.overallLevel);if(profile.repositoryCount!=null)must<HTMLElement>('#repoCount').textContent=`${profile.repositoryCount} VERIFIED`}
function setConnection(state:'checking'|'connected'|'disconnected'|'error',title:string,detail:string){const root=must<HTMLElement>('#connectionStatus');root.dataset.state=state;must<HTMLElement>('#connectionTitle').textContent=title;must<HTMLElement>('#connectionDetail').textContent=detail;logoutButton.hidden=state!=='connected'}
function closeDrawer(){drawer.classList.remove('open');backdrop.classList.remove('open');drawer.setAttribute('aria-hidden','true')}

function openSkill(key:SkillKey){const skill=skills[key];must<HTMLElement>('#skillTitle').textContent=skill.title;must<HTMLElement>('#skillLevel').textContent=skill.level?String(skill.level):'?';must<HTMLElement>('#whyLevel').textContent=skill.level?String(skill.level):'?';must<HTMLElement>('#skillConfidence').textContent=skill.confidence?`${skill.confidence}%`:'NO SIGNAL';must<HTMLElement>('#confidenceBar').style.width=`${skill.confidence}%`;must<HTMLElement>('#skillReason').textContent=skill.reason;
  const capabilityRoot=must<HTMLElement>('#capabilities');capabilityRoot.replaceChildren(...skill.capabilities.map(([state,name])=>{const badge=document.createElement('span');if(state!=='✓')badge.className='missing';badge.textContent=`${state} ${name}`;return badge}));must<HTMLElement>('#evidenceCount').textContent=`${String(skill.evidence.length).padStart(2,'0')} SIGNALS`;
  const list=must<HTMLElement>('#evidenceList');if(!skill.evidence.length){const empty=document.createElement('article');empty.className='evidence-item';const p=document.createElement('p');p.textContent='No inspectable evidence found in the indexed repositories.';empty.append(p);list.replaceChildren(empty)}else list.replaceChildren(...skill.evidence.map(evidence=>{const item=document.createElement('article');item.className='evidence-item';const label=document.createElement('span');label.textContent=`◆ VERIFIED PATTERN / ${evidence.capability}`;const summary=document.createElement('p');summary.textContent=evidence.summary;const link=document.createElement('a');link.href=evidence.url;link.target='_blank';link.rel='noreferrer';const code=document.createElement('code');code.textContent=`${evidence.repository} / ${evidence.path} : ${evidence.line} ↗`;link.append(code);item.append(label,summary,link);return item}));
  must<HTMLElement>('#nextLevel').textContent=skill.next;drawer.classList.add('open');backdrop.classList.add('open');drawer.setAttribute('aria-hidden','false')}

function renderAnalysis(data:AnalysisResult){skills={...skills,...data.skills};for(const [key,skill] of Object.entries(data.skills) as Array<[SkillKey,Skill]>){const node=document.querySelector<HTMLButtonElement>(`[data-skill="${key}"]`);if(!node)continue;child<HTMLElement>(node,'.node-ring b').textContent=skill.score?String(skill.score):'?';child<HTMLElement>(node,'.node-ring small').textContent=skill.level?`LV.${skill.level}`:'LOCKED';child<HTMLElement>(node,':scope > small').textContent=skill.level?`${skill.evidence.length} EVIDENCE`:'NO SIGNAL';node.classList.toggle('locked',skill.level===0);node.classList.toggle('emerging',skill.level>0&&skill.level<6)}setProfile(data.profile);must<HTMLElement>('#scanState').textContent=data.aiReview.used?'AI VERIFIED':'CODE INDEXED';must<HTMLElement>('#scanTime').textContent=new Date(data.scannedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});must<HTMLElement>('.tree-count').textContent=`${Object.values(data.skills).filter(skill=>skill.level>0).length} / ${skillKeys.length} NODES DISCOVERED`;syncButton.innerHTML='RESCAN CODE <span>↗</span>'}

const stageCopy:Record<ScanStage,{title:string;detail:string;log:string}>={queued:{title:'Scan queued',detail:'Waiting for the local analysis worker.',log:'QUEUED'},repositories:{title:'Reading repositories',detail:'Selecting relevant source files from your active projects.',log:'INDEXING REPOSITORIES'},evidence:{title:'Finding code evidence',detail:'Matching implemented patterns to verifiable capabilities.',log:'EXTRACTING CODE SIGNALS'},ai_review:{title:'Local AI review',detail:'Ollama is challenging the rule-based score against real snippets.',log:'OLLAMA REVIEW'},scoring:{title:'Building your skill graph',detail:'Combining repetition and depth into verified levels.',log:'CALCULATING LEVELS'},completed:{title:'Skill graph ready',detail:'Every visible level now links back to code evidence.',log:'VERIFIED BY CODE'},failed:{title:'Scan stopped',detail:'The current stage could not be completed.',log:'ACTION REQUIRED'}};
function renderScan(job:ScanRecord){const stage:ScanStage=job.status==='failed'?'failed':job.status==='completed'?'completed':job.stage;const copy=stageCopy[stage];must<HTMLElement>('#scanTitle').textContent=copy.title;must<HTMLElement>('#scanDetail').textContent=job.error||copy.detail;must<HTMLElement>('#scanLog').textContent=copy.log;must<HTMLElement>('#scanPercent').textContent=`${job.progress}%`;must<HTMLElement>('#scanProgress').style.width=`${job.progress}%`;const order:ScanStage[]=['repositories','evidence','ai_review','scoring'];const current=order.indexOf(stage);document.querySelectorAll<HTMLElement>('#scanSteps li').forEach((step,index)=>{step.classList.toggle('active',index===current);step.classList.toggle('done',stage==='completed'||index<current)});scanRetry.hidden=job.status!=='failed';scanClose.hidden=job.status!=='failed'&&job.status!=='completed'}
function openScan(){activeScan=true;scanOverlay.classList.add('open');scanOverlay.setAttribute('aria-hidden','false')}
function closeScan(){activeScan=false;scanOverlay.classList.remove('open');scanOverlay.setAttribute('aria-hidden','true')}
async function followScan(initial:ScanRecord){openScan();let job=initial;renderScan(job);while(job.status==='queued'||job.status==='running'){await new Promise(resolve=>setTimeout(resolve,1200));job=await api<ScanRecord>(`/api/scans/${job.id}`);renderScan(job)}if(job.status==='failed')throw new Error(job.error||'Scan failed');if(!job.result)throw new Error('The scan completed without a result');renderAnalysis(job.result);renderScan(job);showToast(`${job.result.filesInspected} files verified${job.result.aiReview.used?` with ${job.result.aiReview.model}`:''}`);setTimeout(closeScan,900)}
async function runScan(){syncButton.disabled=true;try{const job=await api<ScanRecord>('/api/analyze',{method:'POST'});await followScan(job)}catch(error){const message=error instanceof Error?error.message:'Scan failed';renderScan({id:'',status:'failed',stage:'failed',progress:0,result:null,error:message});openScan();showToast(message)}finally{syncButton.disabled=false;history.replaceState({},'',location.pathname)}}
async function getAuthState():Promise<AuthState>{try{return await api<AuthState>('/api/auth/status')}catch{setConnection('error','Local API is offline','Run docker compose up --build -d, then retry.');return{connected:false,user:null,oauthConfigured:false,unavailable:true}}}
async function handleConnectAction(){syncButton.disabled=true;const state=await(authStatePromise||getAuthState());if(state.connected){syncButton.disabled=false;await runScan();return}if(state.unavailable){syncButton.disabled=false;showToast('Local API is offline');return}if(!state.oauthConfigured){syncButton.disabled=false;setConnection('error','GitHub OAuth is not configured','Add the client ID and secret to .env, then restart Docker.');showToast('GitHub OAuth credentials are missing');return}location.assign('/api/auth/github')}
async function initialize(){setConnection('checking','Checking local services…','Reading your GitHub connection and latest scan.');authStatePromise=getAuthState();const state=await authStatePromise;if(!state.connected||!state.user){syncButton.innerHTML='CONNECT GITHUB <span>↗</span>';if(!state.unavailable)setConnection('disconnected','GitHub is not connected','Authorize read access to build a verified skill graph.');const error=new URLSearchParams(location.search).get('error');if(error)showToast(error==='oauth_state'?'GitHub authorization expired — try again':'GitHub authorization failed — try again');return}setProfile(state.user);syncButton.innerHTML='SCAN MY CODE <span>↗</span>';setConnection('connected',`Connected as @${state.user.login}`,'Scans run locally; GitHub tokens are encrypted at rest.');try{const latest=await api<ScanRecord|null>('/api/scans/latest');if(latest?.status==='completed'&&latest.result)renderAnalysis(latest.result);if(latest&&(latest.status==='queued'||latest.status==='running'))await followScan(latest)}catch(error){showToast(error instanceof Error?error.message:'Could not restore the latest scan')}if(new URLSearchParams(location.search).has('connected'))await runScan()}

document.querySelectorAll<HTMLButtonElement>('.skill-node').forEach(node=>node.addEventListener('click',()=>openSkill(node.dataset.skill as SkillKey)));must<HTMLButtonElement>('#drawerClose').addEventListener('click',closeDrawer);backdrop.addEventListener('click',closeDrawer);document.querySelectorAll<HTMLButtonElement>('.tree-toolbar button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.tree-toolbar button').forEach(item=>item.classList.remove('active'));button.classList.add('active');document.querySelectorAll<HTMLButtonElement>('.skill-node').forEach(node=>node.classList.toggle('hidden',button.dataset.filter!=='all'&&node.dataset.domain!==button.dataset.filter))}));must<HTMLButtonElement>('#explainBtn').addEventListener('click',()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false')});must<HTMLButtonElement>('#modalClose').addEventListener('click',()=>modal.classList.remove('open'));modal.addEventListener('click',event=>{if(event.target===modal)modal.classList.remove('open')});document.querySelectorAll<HTMLButtonElement>('[data-toast]').forEach(button=>button.addEventListener('click',()=>showToast(button.dataset.toast||'Done')));syncButton.addEventListener('click',handleConnectAction);scanRetry.addEventListener('click',runScan);scanClose.addEventListener('click',closeScan);logoutButton.addEventListener('click',async()=>{await api('/api/auth/logout',{method:'POST'});location.assign('/')});must<HTMLButtonElement>('#profileAvatar').addEventListener('click',()=>{must<HTMLElement>('.passport-card').scrollIntoView({behavior:'smooth',block:'center'});showToast('Developer Passport — verified from your GitHub code')});document.addEventListener('keydown',event=>{if(event.key!=='Escape')return;closeDrawer();modal.classList.remove('open');if(!activeScan||!scanRetry.hidden||!scanClose.hidden)closeScan()});void initialize();
