import type { AnalysisResult, AuthState, DeveloperProfile, Quest, ScanRecord, ScanStage, Skill, SkillKey } from '../shared/types.js';
import { applyTranslations, getLocale, setLocale, t, type MessageKey } from './i18n.js';

type UiSkill = Omit<Skill, 'score' | 'repositoryCount' | 'evidenceScore'> & { score?: number; repositoryCount?: number; evidenceScore?: number };
const skillKeys: SkillKey[] = ['python', 'fastapi', 'api', 'llm', 'testing', 'database', 'rag', 'agents', 'evaluation'];
const demo = (title: string, level: number, confidence: number, reason: string, capabilities: Skill['capabilities'], next: string): UiSkill => ({ title, level, confidence, reason, capabilities, next, evidence: [] });
let skills: Record<SkillKey, UiSkill> = {
  python: demo('PYTHON',9,97,'Advanced Python patterns appear across async services, typed models, packaging and data pipelines.',[['✓','Async IO'],['✓','Type System'],['✓','Packaging'],['✓','Data Models'],['△','Profiling']],'Show production profiling evidence to reach Level 10.'),
  fastapi: demo('FASTAPI',8,94,'Repeated production use of async APIs, dependency injection, middleware, authentication and streaming responses.',[['✓','Async API'],['✓','Dependency Injection'],['✓','Middleware'],['✓','Authentication'],['✓','SSE'],['△','Testing'],['✕','Observability']],'Add integration tests and observability to reach Level 9.'),
  api: demo('API DESIGN',8,91,'The APIs use consistent resources, structured errors, versioning and streaming.',[['✓','REST'],['✓','Versioning'],['✓','Error Models'],['✓','Streaming'],['△','Rate Limits']],'Implement rate limits and publish a compatibility policy.'),
  llm: demo('LLM',6,86,'Model providers, streaming and prompt templates are implemented; evaluation evidence is still missing.',[['✓','Streaming'],['✓','Providers'],['✓','Prompting'],['△','Guardrails'],['✕','Evaluation']],'Add a versioned evaluation harness.'),
  testing: demo('TESTING',2,88,'Current evidence covers utilities but not enough service behavior.',[['✓','Unit Tests'],['△','Fixtures'],['✕','API Integration'],['✕','Mocking'],['✕','Coverage']],'Complete The Testing Dungeon.'),
  database: demo('DATABASES',7,89,'Schema design, migrations, transactions and optimized queries appear across multiple projects.',[['✓','PostgreSQL'],['✓','Migrations'],['✓','Transactions'],['✓','Indexes'],['△','Replication']],'Show partitioning or replication decisions.'),
  rag: demo('RAG',5,82,'Chunking, embeddings and retrieval are implemented with limited quality measurement.',[['✓','Chunking'],['✓','Embeddings'],['✓','Vector Search'],['△','Reranking'],['✕','Evaluation']],'Add retrieval evaluation and reranking.'),
  agents: demo('AGENTS',4,78,'Tool calling and orchestration exist; durable state and recovery remain limited.',[['✓','Tool Calling'],['✓','Planning'],['△','State'],['✕','Recovery'],['✕','Evaluation']],'Implement durable state and replay.'),
  evaluation: demo('EVALUATION',0,0,'No reliable code signal has been discovered. This is unknown, not a negative assessment.',[['✕','Datasets'],['✕','Metrics'],['✕','Regression'],['✕','Tracing']],'Ship a small versioned evaluation suite.')
};

function must<T extends Element>(selector: string): T { const node=document.querySelector<T>(selector); if(!node)throw new Error(`Missing UI element: ${selector}`); return node; }
function child<T extends Element>(root: Element, selector: string): T { const node=root.querySelector<T>(selector); if(!node)throw new Error(`Missing child: ${selector}`); return node; }
const drawer=must<HTMLElement>('#evidenceDrawer'), backdrop=must<HTMLElement>('#drawerBackdrop'), modal=must<HTMLElement>('#scoreModal');
const toast=must<HTMLElement>('#toast'), syncButton=must<HTMLButtonElement>('#syncGithub'), logoutButton=must<HTMLButtonElement>('#logoutButton');
const scanOverlay=must<HTMLElement>('#scanOverlay'), scanRetry=must<HTMLButtonElement>('#scanRetry'), scanClose=must<HTMLButtonElement>('#scanClose');
let toastTimer: ReturnType<typeof setTimeout>|undefined, authStatePromise: Promise<AuthState>|undefined, activeScan=false;
let currentProfile: DeveloperProfile|undefined, currentAnalysis: AnalysisResult|undefined, currentJob: ScanRecord|undefined, currentSkill: SkillKey|undefined;
let currentQuest: Quest|undefined;
let connectionView: {state:'checking'|'connected'|'disconnected'|'error';title:MessageKey;detail:MessageKey;params?:Record<string,string|number>}|undefined;

function showToast(message:string){must<HTMLElement>('#toast b').textContent=message;toast.classList.add('show');if(toastTimer)clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),3200)}
async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(path,{cache:'no-store',...init});const data=await response.json().catch(()=>({})) as T&{error?:string};if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data}
function initials(name:string){return name.split(/\s+/).filter(Boolean).map(part=>part[0]||'').join('').slice(0,2).toUpperCase()}
function setAction(label:MessageKey){syncButton.replaceChildren(document.createTextNode(t(label)),Object.assign(document.createElement('span'),{textContent:'↗'}))}
function setProfile(profile:DeveloperProfile){currentProfile=profile;const name=(profile.name||profile.login||'Developer').trim();must<HTMLElement>('#passportName').innerHTML=name.split(/\s+/).join('<br>');must<HTMLElement>('#profileAvatar').textContent=initials(name);if(profile.overallLevel)must<HTMLElement>('#overallLevel').textContent=String(profile.overallLevel);if(profile.repositoryCount!=null)must<HTMLElement>('#repoCount').textContent=t('count.repositories',{count:profile.repositoryCount})}
function setConnection(state:'checking'|'connected'|'disconnected'|'error',title:MessageKey,detail:MessageKey,params:Record<string,string|number>={}){connectionView={state,title,detail,params};const root=must<HTMLElement>('#connectionStatus');root.dataset.state=state;must<HTMLElement>('#connectionTitle').textContent=t(title,params);must<HTMLElement>('#connectionDetail').textContent=t(detail,params);logoutButton.hidden=state!=='connected'}
function closeDrawer(){drawer.classList.remove('open');backdrop.classList.remove('open');drawer.setAttribute('aria-hidden','true')}

function openSkill(key:SkillKey){currentSkill=key;const skill=skills[key];must<HTMLElement>('#skillTitle').textContent=skill.title;must<HTMLElement>('#skillLevel').textContent=skill.level?String(skill.level):'?';must<HTMLElement>('#whyHeading').textContent=t('drawer.why',{level:skill.level||'?'});must<HTMLElement>('#skillConfidence').textContent=skill.confidence?`${skill.confidence}%`:t('count.none');must<HTMLElement>('#confidenceBar').style.width=`${skill.confidence}%`;must<HTMLElement>('#skillReason').textContent=skill.reason;
  const capabilityRoot=must<HTMLElement>('#capabilities');capabilityRoot.replaceChildren(...skill.capabilities.map(([state,name])=>{const badge=document.createElement('span');if(state!=='✓')badge.className='missing';badge.textContent=`${state} ${name}`;return badge}));must<HTMLElement>('#evidenceCount').textContent=t('drawer.signals',{count:String(skill.evidence.length).padStart(2,'0')});
  const list=must<HTMLElement>('#evidenceList');if(!skill.evidence.length){const empty=document.createElement('article');empty.className='evidence-item';const p=document.createElement('p');p.textContent=t('drawer.empty');empty.append(p);list.replaceChildren(empty)}else list.replaceChildren(...skill.evidence.map(evidence=>{const item=document.createElement('article');item.className='evidence-item';const label=document.createElement('span');label.textContent=`◆ ${evidence.capability}`;const summary=document.createElement('p');summary.textContent=evidence.summary;const link=document.createElement('a');link.href=evidence.url;link.target='_blank';link.rel='noreferrer';const code=document.createElement('code');code.textContent=`${evidence.repository} / ${evidence.path} : ${evidence.line} ↗`;link.append(code);item.append(label,summary,link);return item}));
  must<HTMLElement>('#nextLevel').textContent=skill.next;drawer.classList.add('open');backdrop.classList.add('open');drawer.setAttribute('aria-hidden','false')}

function renderAnalysis(data:AnalysisResult){currentAnalysis=data;skills={...skills,...data.skills};for(const [key,skill] of Object.entries(data.skills) as Array<[SkillKey,Skill]>){const node=document.querySelector<HTMLButtonElement>(`[data-skill="${key}"]`);if(!node)continue;child<HTMLElement>(node,'.node-ring b').textContent=skill.score?String(skill.score):'?';child<HTMLElement>(node,'.node-ring small').textContent=skill.level?`LV.${skill.level}`:'LOCKED';child<HTMLElement>(node,':scope > small').textContent=skill.level?t('count.evidence',{count:skill.evidence.length}):t('count.none');node.classList.toggle('locked',skill.level===0);node.classList.toggle('emerging',skill.level>0&&skill.level<6)}setProfile(data.profile);must<HTMLElement>('#scanState').textContent=data.aiReview.used?'AI VERIFIED':'CODE INDEXED';must<HTMLElement>('#scanTime').textContent=new Date(data.scannedAt).toLocaleTimeString(getLocale()==='zh'?'zh-CN':'en',{hour:'2-digit',minute:'2-digit'});must<HTMLElement>('.tree-count').textContent=t('count.nodes',{verified:Object.values(data.skills).filter(skill=>skill.level>0).length,total:skillKeys.length});setAction('action.rescan');void loadQuest()}

function renderQuest(quest:Quest){currentQuest=quest;must<HTMLElement>('#questTitle').textContent=t(`quest.name.${quest.skillKey}` as MessageKey);must<HTMLElement>('#questDescription').textContent=t('quest.generatedDescription',{skill:skills[quest.skillKey].title});const objectives=must<HTMLElement>('#questObjectives');objectives.replaceChildren(...quest.objectives.map(objective=>{const label=document.createElement('label');const input=document.createElement('input');input.type='checkbox';input.checked=objective.completed;input.disabled=true;const text=document.createElement('span');text.textContent=objective.label;const xp=document.createElement('em');xp.textContent=`+${objective.xp} XP`;label.append(input,text,xp);return label}));must<HTMLElement>('#questReward').innerHTML=`+${quest.rewardXp} <small>XP</small>`;must<HTMLElement>('#questTarget').textContent=`${skills[quest.skillKey].title} · ${quest.repositoryFullName}`;must<HTMLElement>('#questNote').textContent=quest.baselineSha?t('quest.repository',{repository:quest.repositoryFullName}):t('quest.freshScan');const accept=must<HTMLButtonElement>('#acceptQuest');accept.disabled=quest.status!=='proposed'||!quest.baselineSha;accept.textContent=t(quest.status==='completed'?'quest.completed':quest.status==='accepted'?'quest.active':'quest.accept')}

async function loadQuest(){try{const existing=await api<Quest|null>('/api/quests/current');if(existing){renderQuest(existing);return}renderQuest(await api<Quest>('/api/quests/recommended'))}catch{/* A first scan is required before quests can be generated. */}}

const stageCopy:Record<ScanStage,{title:MessageKey;detail:MessageKey;log:string}>={queued:{title:'scan.queued.title',detail:'scan.queued.detail',log:'QUEUED'},repositories:{title:'scan.repositories.title',detail:'scan.repositories.detail',log:'INDEXING REPOSITORIES'},evidence:{title:'scan.evidence.title',detail:'scan.evidence.detail',log:'EXTRACTING CODE SIGNALS'},ai_review:{title:'scan.ai_review.title',detail:'scan.ai_review.detail',log:'OLLAMA REVIEW'},scoring:{title:'scan.scoring.title',detail:'scan.scoring.detail',log:'CALCULATING LEVELS'},completed:{title:'scan.completed.title',detail:'scan.completed.detail',log:'VERIFIED BY CODE'},failed:{title:'scan.failed.title',detail:'scan.failed.detail',log:'ACTION REQUIRED'}};
function renderScan(job:ScanRecord){currentJob=job;const stage:ScanStage=job.status==='failed'?'failed':job.status==='completed'?'completed':job.stage;const copy=stageCopy[stage];must<HTMLElement>('#scanTitle').textContent=t(copy.title);must<HTMLElement>('#scanDetail').textContent=job.error||t(copy.detail);must<HTMLElement>('#scanLog').textContent=copy.log;must<HTMLElement>('#scanPercent').textContent=`${job.progress}%`;must<HTMLElement>('#scanProgress').style.width=`${job.progress}%`;const order:ScanStage[]=['repositories','evidence','ai_review','scoring'];const current=order.indexOf(stage);document.querySelectorAll<HTMLElement>('#scanSteps li').forEach((step,index)=>{step.classList.toggle('active',index===current);step.classList.toggle('done',stage==='completed'||index<current)});scanRetry.hidden=job.status!=='failed';scanClose.hidden=job.status!=='failed'&&job.status!=='completed'}
function openScan(){activeScan=true;scanOverlay.classList.add('open');scanOverlay.setAttribute('aria-hidden','false')}
function closeScan(){activeScan=false;scanOverlay.classList.remove('open');scanOverlay.setAttribute('aria-hidden','true')}
async function followScan(initial:ScanRecord){openScan();let job=initial;renderScan(job);while(job.status==='queued'||job.status==='running'){await new Promise(resolve=>setTimeout(resolve,1200));job=await api<ScanRecord>(`/api/scans/${job.id}`);renderScan(job)}if(job.status==='failed')throw new Error(job.error||'Scan failed');if(!job.result)throw new Error('The scan completed without a result');renderAnalysis(job.result);renderScan(job);showToast(t('scan.verified',{count:job.result.filesInspected,model:job.result.aiReview.used?` · ${job.result.aiReview.model}`:''}));setTimeout(closeScan,900)}
async function runScan(){syncButton.disabled=true;try{const job=await api<ScanRecord>('/api/analyze',{method:'POST'});await followScan(job)}catch(error){const message=error instanceof Error?error.message:'Scan failed';renderScan({id:'',status:'failed',stage:'failed',progress:0,result:null,error:message});openScan();showToast(message)}finally{syncButton.disabled=false;history.replaceState({},'',location.pathname)}}
async function getAuthState():Promise<AuthState>{try{return await api<AuthState>('/api/auth/status')}catch{setConnection('error','connection.offline.title','connection.offline.detail');return{connected:false,user:null,oauthConfigured:false,unavailable:true}}}
async function handleConnectAction(){syncButton.disabled=true;const state=await(authStatePromise||getAuthState());if(state.connected){syncButton.disabled=false;await runScan();return}if(state.unavailable){syncButton.disabled=false;showToast(t('toast.offline'));return}if(!state.oauthConfigured){syncButton.disabled=false;setConnection('error','connection.oauth.title','connection.oauth.detail');showToast(t('toast.oauth'));return}location.assign('/api/auth/github')}
async function initialize(){applyTranslations();setConnection('checking','connection.checking.title','connection.checking.detail');authStatePromise=getAuthState();const state=await authStatePromise;if(!state.connected||!state.user){setAction('action.connect');if(!state.unavailable)setConnection('disconnected','connection.disconnected.title','connection.disconnected.detail');const error=new URLSearchParams(location.search).get('error');if(error)showToast(t(error==='oauth_state'?'toast.authExpired':'toast.authFailed'));return}setProfile(state.user);setAction('action.scan');setConnection('connected','connection.connected.title','connection.connected.detail',{login:state.user.login});try{const latest=await api<ScanRecord|null>('/api/scans/latest');if(latest?.status==='completed'&&latest.result)renderAnalysis(latest.result);if(latest&&(latest.status==='queued'||latest.status==='running'))await followScan(latest)}catch(error){showToast(error instanceof Error?error.message:'Could not restore the latest scan')}if(new URLSearchParams(location.search).has('connected'))await runScan()}

document.querySelectorAll<HTMLButtonElement>('.skill-node').forEach(node=>node.addEventListener('click',()=>openSkill(node.dataset.skill as SkillKey)));must<HTMLButtonElement>('#drawerClose').addEventListener('click',closeDrawer);backdrop.addEventListener('click',closeDrawer);document.querySelectorAll<HTMLButtonElement>('.tree-toolbar button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.tree-toolbar button').forEach(item=>item.classList.remove('active'));button.classList.add('active');document.querySelectorAll<HTMLButtonElement>('.skill-node').forEach(node=>node.classList.toggle('hidden',button.dataset.filter!=='all'&&node.dataset.domain!==button.dataset.filter))}));must<HTMLButtonElement>('#explainBtn').addEventListener('click',()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false')});must<HTMLButtonElement>('#modalClose').addEventListener('click',()=>modal.classList.remove('open'));modal.addEventListener('click',event=>{if(event.target===modal)modal.classList.remove('open')});document.querySelectorAll<HTMLButtonElement>('[data-toast-key]').forEach(button=>button.addEventListener('click',()=>showToast(t(button.dataset.toastKey as MessageKey))));must<HTMLButtonElement>('#acceptQuest').addEventListener('click',async()=>{try{renderQuest(await api<Quest>('/api/quests/accept',{method:'POST'}));showToast(t('toast.quest'))}catch(error){showToast(error instanceof Error?error.message:'Quest could not be accepted')}});syncButton.addEventListener('click',handleConnectAction);scanRetry.addEventListener('click',runScan);scanClose.addEventListener('click',closeScan);logoutButton.addEventListener('click',async()=>{await api('/api/auth/logout',{method:'POST'});location.assign('/')});must<HTMLButtonElement>('#profileAvatar').addEventListener('click',()=>{must<HTMLElement>('.passport-card').scrollIntoView({behavior:'smooth',block:'center'});showToast(t('toast.passport'))});must<HTMLButtonElement>('#languageToggle').addEventListener('click',()=>setLocale(getLocale()==='en'?'zh':'en'));document.addEventListener('devtree:localechange',()=>{if(connectionView)setConnection(connectionView.state,connectionView.title,connectionView.detail,connectionView.params);if(currentAnalysis)renderAnalysis(currentAnalysis);else if(currentProfile)setProfile(currentProfile);if(currentJob)renderScan(currentJob);if(currentSkill&&drawer.classList.contains('open'))openSkill(currentSkill);if(currentQuest)renderQuest(currentQuest)});document.addEventListener('keydown',event=>{if(event.key!=='Escape')return;closeDrawer();modal.classList.remove('open');if(!activeScan||!scanRetry.hidden||!scanClose.hidden)closeScan()});void initialize();
